language: node_js
node_js: node
services: mongodb
deploy:
  provider: firebase
  token:
    secure: d0lH7FSL3BwaiIrWPAENVHqXKkYvHHISBTc3yKlltgOMzKW32TMrXGc0BAqj/0CgkwoykJsKMIjgQRyCCnDZp/wCNypxkgWbnamO4gENKau9KuqT5ZQ4HpTWtCbnJfVe5uxr0QtrYGR/E4ldk/vXrCQEkt9dEXcpwHx2G8qrtrsPEbp6TvqOwDR+o+JpUaArhut+2IL9FSHlgidGFUEqCuDI8crC0RtpBWgotiGR/BgModecYHRjbe5DSzKwFS+MwjPjph5EEVcKk3l34J6DTXDiBgPeCz0HDlsEZ03TpdJzheAiDXm8lZsMZtyhtbhBzu1SOm7GVrN0YbhAvO+CMXbGc/uUA6MZlXzN5BzS1ThpS4FIjflWVK7EHARA7rh0iHfPr0QPk0jP91T3NYbgTIEy5i01AvxJ6wjeE18km+tmQlCEo3yAjcnjoNJfzrE3ikmLg1XKfxGlZiyi+XWRDfFK84Oi9irEX38h1W1lTp0bX2JT6NINctb6clnKA0F33xhycfo8w4VE7KfMDBKn0E6M54TLceqTREYAF0MbRnzpytCxNbp8p3oAigx4I6DsW2EOuElZG82KkOWAMIiCsN8fYZXzV8vo80CUxozAq8LT6GzlQs6rXsxEpaO0O7I/dxSiwpZZ3dMfvkcVTXhVl3S+tU2kkz3EuoghJTHyRF8=
  project: 'sputnik-server'
