language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: fy8dGXwTZCDGMFBygzMOZM2DIuQYE/LJTDPmuNVd5EdGA9Aj/hm+vSwmNyX0g5XBRJe9CRdGWpu27Y344fTtDnIS7JTlPOb57E+YVKKY2ohHspPpXeWk3itbxFdgJAWfOS7Gjr9WF5yvIy14aSqPBT1yNFOTXj++cy2+xWTgOTuGpcWcsYJbvZ4DGx6Rn53yICUHYqpMacRrLFvAtX6L2t/fSRvBJhfQqyId3f5KAoK+XvYsc44O8Udl8Gcrvs8gR18SHR88yGivw9a8KOs3C5Mp7EU9hR8ZfNiwWmL+LzN72c8ddMvWFdOLSgw9RE9SYoGtBk8qQKKOuNhscqMGB0vuYdPNMWTnZEym2r09qUErxN1Af25DntHGqa3o82B2SVUMqOyI0wtSs4QK46Yz+5JhjEGY1FiaHuDMiyhWTxA63QzHO2fge3oXZCiaMQITqtatVdYg4nIkjYmvKb4qfSLY50G/CZ6YVvRRnHdIqw2YAi5zVT5KB/N+8XuVFV/tF+LNiapca6CmZOlyvJrmExDHMfffKBdSlDf22jd6PJpwdIZwotZIw6HqQxqXcxY8SdRwI/J4Q/nrGeg+9/of+vUl80RaY0f0nd+LhCOrf3cmDQZ6+ypCHv4PeUYld6PVDm2TOfz1TQ86Wa4RkpNdkhxlt1RYQWxWvQGH9u+foek=
  app: sputnik-server
  on:
    repo: rcmaples/sputnik-server
